---
- name: Install Notepad++ and 7zip via Chocolatey.
  hosts: all
  
  tasks:
  
  - name: Install multiple packages.
    win_chocolatey:
      name:
      - notepadplusplus
      - 7zip.install
      state: present